name: Test Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check SONAR_HOST_URL
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          if (-not $env:SONAR_HOST_URL) {
            Write-Host "❌ SONAR_HOST_URL is EMPTY"
          } else {
            Write-Host "✅ SONAR_HOST_URL is set to: $env:SONAR_HOST_URL"
          }

      - name: Check SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if (-not $env:SONAR_TOKEN) {
            Write-Host "❌ SONAR_TOKEN is EMPTY"
          } else {
            Write-Host "✅ SONAR_TOKEN is set (value hidden for security)"
          }
